import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"

import { ClerkProvider } from "@clerk/nextjs"

import "@/styles/globals.css"

import { TanstackProvider } from "@/components/providers/tanstack"

import { Toaster } from "@/components/ui/sonner"
import { Loader2 } from "lucide-react"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Scrape.io",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider afterSignOutUrl="/auth/sign-in">
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans`}
        >
          <TanstackProvider>{children}</TanstackProvider>
          <Toaster
            theme="light"
            richColors={true}
            closeButton={true}
            icons={{
              loading: <Loader2 className="animate-spin" size={16} />,
            }}
            toastOptions={{
              className: "rounded-none",
            }}
          />
        </body>
      </html>
    </ClerkProvider>
  )
}
